# Generated by Django 6.0.4 on 2026-04-14 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_full_name', models.CharField(max_length=255, verbose_name='ПІБ пацієнта')),
                ('patient_birth_date', models.DateField(verbose_name='Дата народження')),
                ('patient_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('complaints', models.TextField(verbose_name='Скарги')),
                ('appointment_date', models.DateTimeField(verbose_name='Дата прийому')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Діагноз')),
                ('treatment_description', models.TextField(verbose_name='Опис лікування')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctor', verbose_name='Лікар')),
            ],
            options={
                'verbose_name': 'Запис до лікаря',
                'verbose_name_plural': 'Записи до лікаря',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
