# Generated by Django 6.0.4 on 2026-04-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('specialization', models.CharField(max_length=255, verbose_name='Спеціалізація')),
                ('years_of_experience', models.PositiveIntegerField(verbose_name='Стаж (років)')),
            ],
            options={
                'verbose_name': 'Лікар',
                'verbose_name_plural': 'Лікарі',
                'ordering': ['full_name'],
            },
        ),
    ]
